#pragma once

#include <types>

enum class Action : u8 {
    Quit,
    ToggleConsole,
    EnterCommand,
    ConsoleBackspace,
    ConsoleDelete,
    ConsoleCursorLeft,
    ConsoleCursorRight,
    ConsoleHistoryOlder,
    ConsoleHistoryNewer,
    ViewportOrbit,
    ViewportPan,
    ViewportZoom,
    VertexMode,
    EdgeMode,
    FaceMode,
    Select,
    AddSelection,
    RemoveSelection,
    GrabSelection,
    ConfirmGrab,
    CancelGrab,
    ScaleSelection,
    ConfirmScale,
    CancelScale,
    ExtrudeSelection,
    InsetSelection,
    DeleteSelection,
    FillFaceLoop,
    ConnectVertices,
    RotateSelection,
    RotateConfirm,
    RotateCancel,
    BevelSelection,
    ConfirmBevel,
    CancelBevel,
    XAxis,
    YAxis,
    ZAxis,
    Count
};